apiVersion: apps/v1
kind: Deployment
metadata:
  name: satish-deployment
  labels: 
    app: suji
spec:
  minReadySeconds: 15
  replicas: 5
  selector:
    matchLabels:
      app: suji
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: satishpod-deploy
      labels:
        app: suji
        version: 2.60.3
    spec:
      containers:
        - name: satishcontainer-deploy
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080
              protocol: TCP    

