apiVersion: apps/v1
kind: Deployment
metadata:
  name: satish-deployment
  labels: 
    app: suji
spec:
  minReadySeconds: 15
  replicas: 5
  selector:
    matchLabels:
      app: suji
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      name: satishpod-deploy
      labels:
        app: suji
    spec:
      containers:
        - name: satishcontainer-deploy
          image: jenkins/jenkins:2.438-alpine-jdk21
          ports:
            - containerPort: 8080
              protocol: TCP    

