---
apiVersion: v1
kind: Pod
metadata:
  name: satish-pod
  labels:
    app: nginx
spec:
  containers:
    - name: satish-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
             
         

