---
apiVersion: v1
kind: Pod
metadata:
  name: satish-pod
  labels:
    app: suji
spec:
  - containers:
      name: satish-cont
      image: bitcoinv1
      ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: satish-service
  labels:
    app: suji
spec:
  - ports:
      - NodePort: 32006
        port: 35000
        targetport: 80
    selector:
      app: dev
    type: NodePort      
           