---
apiVersion: v1
kind: Pod
metadata:
  name: preethi-pod
  labels:
    app: preethi
spec:
  containers:
    - name: suji-cont
      image: satishgavva/dockerchange:bitcoinv1
      ports:
        - containerPort: 80
          protocol: TCP
             
---
apiVersion: v1
kind: Service
metadata:
  name: preethi-service
  labels:
    app: preethi
spec:
  ports:
    - nodePort: 32006
      port: 35000
      targetPort: 80
  selector: 
    app: preethi  
  type: NodePort               

