---
apiVersion: v1
kind: Pod
metadata:
  name: satish-pod
  labels:
    app: suji
spec:
  containers:
    - name: satish-cont
      image: satishgavva/dockerchange:coffeev1
      ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: satish-service
  labels:
    app: suji
spec:
  ports:
    - nodePort: 32008
      port: 35000
      targetPort: 80
  selector: 
    app: suji   
  type: NodePort  