---
apiVersion: v1
kind: Pod
metadata:
  name: sujata-pod
  labels:
    app: nginx
spec:
  containers:
    - name: suji-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
             
---
apiVersion: v1
kind: Service
metadata:
  name: satish-service
  labels:
    app: nginx
spec:
  ports:
    - nodePort: 32001
      port: 35000
      targetPort: 80
  selector: 
    app: nginx   
  type: NodePort               

