apiVersion : v1
kind : Service
metadata: 
  name: satish-svc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: 32001
      port: 35000
      targetPort: 80
