apiVersion: v1
kind: Service
metadata:
  name: sujata-service
  labels:
    app: suji
spec:
  ports:
    - nodePort: 32008
      port: 35000
      targetPort: 8080
  selector: 
    app: suji  
  type: NodePort   